const listpostTypes = {
    SET_FILTER : 'SET_FILTER',
    SET_LIST_POSTS_RAW: 'SET_LIST_POSTS_RAW',
    SET_LIST_POSTS_RESULT:'SET_LIST_POSTS_RESULT',
    FETCH_POSTS_START: 'FETCH_POSTS_START'
}

export default listpostTypes