const listpostTypes = {
    SET_FILTER : 'SET_FILTER',
    SET_LIST_POSTS_RAW: 'SET_LIST_POSTS_RAW',
    SET_LIST_POSTS_RESULT:'SET_LIST_POSTS_RESULT',
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    SET_IS_LOADING: 'SET_IS_LOADING',
    SET_PAGE: 'SET_PAGE',
    SET_CURRENT_PAGE: 'SET_CURRENT_PAGE',
    SET_PAGE_NB_MAX: 'SET_PAGE_NB_MAX',
}

export default listpostTypes